### ISSUE TITLE
Large PDFs fail due to Puppeteer.pdf() timeout

### ISSUE THREAD

**Issue by carstenschwede** [humanwhocodes/print-ready#43]
Thanks for a great package that was able to print a document where pagedjs-cli failed. I had to to set `timeout: 120000` manually to `PuppeteerPDFOptions` in order to avoid a timeout. It would be great if this timeout could be specified either via a command-line argument or if a reasonable timeout estimate could be set automatically based on the number of pages.

**Comment by nzakas** [comment]
Thanks for the feedback. I don't mind adding a timeout option.

Can you give me an idea of what a "large PDF" means in this context? That would help me test.

**Comment by carstenschwede** [comment]
That would be great. In my case around ~600 pages with the resulting PDF being ~1GB. It contains a lot of high-resolution images, so the determining factor might actually be total image size instead of pure page count. I also had to disable the PagedJS injection in order to register a `beforeParsed` handler to create the TOC - would be great if that would become an option as well.

**Comment by carstenschwede** [comment]
Unfortunately, there does not seem to be a reliable and easy way to measure the memory footprint of a document to use it as an estimate for how long the PDF generation takes. `performance.measureUserAgentSpecificMemory` seems promising but requires specific response headers. `--timeout 0` to disable the timeout altogether seems to be the best take here.

**Comment by nzakas** [comment]
That works. I'll work on adding the flag and let people fiddle with it as they see fit.
